# 
# sample docker-compose configuration file
# requires:
# - a valid settings.yaml file 
#
version: '3.1'
services:
  distill:
    image: noandrea/distill:latest
    container_name: distill
    restart: unless-stopped
    ports:
      - 1804:1804
    volumes:
      - ./data:/data # this is where the database is stored
      - ./settings.yaml:/settings.docker.yaml # this is to override the settings file


