


POST http://localhost:1804/api/short
X-API-KEY: sSftPgEULMt4UWMh8idQgaTiJh9dKlXfdeiB5qcoCxc!ZehVik
Content-Type: application/json

{
    "id": "testtest",
    "url": "https://gist.githubusercontent.com/noandrea/b636b1e8361e5f8f1250240ce0f87fe5/raw/3daa6dd7f5923870e13721ca8412bdae05c25f7e/found",
    "max_requests": 10,
    "url_exhausted": "https://www.thesaurus.com/browse/exhausted",
    "ttl": 3600,
    "url_expired": "https://www.thesaurus.com/browse/expired"
}

###

GET http://localhost:1804/api/stats/testtest
X-API-KEY: sSftPgEULMt4UWMh8idQgaTiJh9dKlXfdeiB5qcoCxc!ZehVik

###

GET http://localhost:1804/testtest
X-API-KEY: sSftPgEULMt4UWMh8idQgaTiJh9dKlXfdeiB5qcoCxc!ZehVik

###

GET http://aet.li/api/stats
X-API-KEY: sSftPgEULMt4UWMh8idQgaTiJh9dKlXfdeiB5qcoCxc!ZehVik