branches:
  only:
  - master
  - develop

language: go
go:
  - "1.13"

env:
  global:
    - DISTILL_SERVER_LISTEN=0.0.0.0
    - DISTILL_SERVER_PORT=1804

install:
  - go get -u golang.org/x/lint/golint 

script:
  - make lint
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

  # Install deepsource CLI
  - curl https://deepsource.io/cli | sh

  # From the root directory, run the report coverage command
  - ./bin/deepsource report --analyzer test-coverage --key go --value-file ./cover.out

jobs:
  include:
    - stage: Tests
      name: Run tests
      if: type != "cron"
      script:
        - make lint
        - make test
    - stage: Test with latest node and compiler
      if: type = "cron"
      script:
        - make lint
        - make test
