# 
# sample docker-compose configuration file
# requires:
# - a valid settings.yaml file 
#
version: '3.1'
services:
  distill:
    image: registry.gitlab.com/welance/oss/distill:latest
    container_name: distill
    restart: unless-stopped
    ports:
      - 1804:1804
    volumes:
      - ./distil.db:/data/db
      - ./settings.yaml:/data/configs/settings.docker.yaml


