#
# Default configuration for Distill v0.0.3-ci-14-gd67560a
# http://github.com/noandrea/distill
#

server:
  apiKey: sSftPgEULMt4UWMh8idQgaTiJh9dKlXfdeiB5qcoCxc!ZehVik
  host: 0.0.0.0
  port: 1804
  dbPath: distill.db
  rootRedirect: https://github.com/noandrea/distill/wikis/welcome
  expiredRedirect: https://github.com/noandrea/distill/wikis/Expired-URL
shortId:
  alphabet: abcdefghkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789
  length: 6
  maxRequests: 0
  ttl: 0
  expireOn: 0001-01-01T00:00:00Z
tuning:
  statsEventsWorkerNum: 1
  statsEventsQueueSize: 2048
  statsCacheSize: 1024
  dbPurgeWritesCount: 2000
  dbGCDeletesCount: 500
  dbGCDiscardRation: 0.5
  URLCaheSize: 2048
  exportIteratorPrefetchSize: 2048
  apiKeyHeaderName: X-API-KEY

#
# Config end
#