# server configuration
server:
  host: "0.0.0.0"
  port: 1804
  apiKey: naiuraoijodmaojorierjaomdaodorpaokda
  rootRedirect: https://mywebsite.com
  dbPath: ./iljl.db

# short id configuration
shortId:
  alphabet: "abcdefghkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789"
  length: 6
  ttl: 0 # 0 means no expiration
  maxRequests: 10 # 0 means no limits
  domain: iljl.li


