# server configuration
server:
  host: "0.0.0.0"
  port: 1804
  api_key: 1234567890abc
  db_path: /data/db

# short id configuration
short_id:
  alphabet: "abcdefghkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789"
  length: 6
  ttl: 0          # default value, 0 means no expiration
  max_requests: 0  # default value, 0 means no limits
  # expire_on: "2019-03-17T22:03:28+01:00"  # default expiration date
  root_redirect_url: https://discover.distill.plus
  expired_redirect_url: https://discover.distill.plus
  exhausted_redirect_url: https://discover.distill.plus


