# server configuration
server:
  host: "0.0.0.0"
  port: 1804
  apiKey: 123123_changeme_changeme
  rootRedirect: https://gitlab.com/welance/oss/distill/wikis/welcome
  expiredRedirect: https://gitlab.com/welance/oss/distill/wikis/Expired-URL
  dbPath: ./distill.db
  enableStats: true

# short id configuration
shortId:
  alphabet: "abcdefghkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789"
  length: 6
  ttl: 0 # 0 means no expiration
  maxRequests: 10 # 0 means no limits


