# server configuration
server:
  host: ilj.li
  port: 1804
  api-key: naiuraoijodmaojorierjaomdaodorpaokda
  root-redirect: https://mywebsite.com
  db-path: ./iljl.db

# short id configuration
short-id:
  alphabet: "abcdefghkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789"
  length: 6
  ttl: 0 # 0 means no expiration
  max-requests: 0 # 0 means no limits

